import { Users, Baby, DoorOpen, UserRound, TrendingUp } from 'lucide-react'
export default function Dashboard({data}) {
 const stats=[['Familias',data.families.length,Users],['Niños',data.children.filter(c=>!c.archived).length,Baby],['Grupos / Salas',data.rooms.length,DoorOpen],['Especialistas',data.staff.length,UserRound]]
 return <div className="flex-1 overflow-y-auto p-6 md:p-8 dot-pattern"><div className="max-w-7xl mx-auto space-y-6">
  <div><h1 className="text-2xl font-bold text-slate-800">Dashboard</h1><p className="text-xs text-slate-500 mt-1">Resumen general de operación de NAMII</p></div>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{stats.map(([label,value,Icon])=><div key={label} className="bg-white/85 backdrop-blur rounded-2xl border border-teal-100/80 shadow-sm p-5"><div className="flex justify-between"><div><div className="text-[11px] text-slate-400 font-semibold uppercase tracking-wide">{label}</div><div className="text-2xl font-bold mt-2 text-slate-800">{value}</div></div><div className="w-10 h-10 rounded-xl bg-teal-50 text-teal-700 flex items-center justify-center"><Icon size={19}/></div></div></div>)}</div>
  <div className="grid lg:grid-cols-2 gap-5"><div className="bg-white/85 rounded-2xl border border-teal-100/80 p-6"><h2 className="font-bold text-slate-800">Ocupación por grupo</h2><p className="text-xs text-slate-500 mb-5">Capacidad actual</p><div className="space-y-4">{data.rooms.map(r=><div key={r.id}><div className="flex justify-between text-xs mb-1.5"><span className="font-semibold text-slate-700">{r.name}</span><span className="text-slate-400">{r.enrolled}/{r.capacity}</span></div><div className="h-2 bg-slate-100 rounded-full overflow-hidden"><div className="h-full bg-teal-600 rounded-full" style={{width:`${Math.min(100,r.enrolled/r.capacity*100)}%`}}/></div></div>)}</div></div>
  <div className="bg-white/85 rounded-2xl border border-teal-100/80 p-6"><div className="flex items-center gap-2"><TrendingUp size={17} className="text-teal-700"/><h2 className="font-bold text-slate-800">Actividad comercial</h2></div><p className="text-xs text-slate-500 mb-5">Leads actuales por etapa</p><div className="grid grid-cols-2 gap-3">{['Consulta','Agenda Clase Muestra','Clase Muestra','Fidelizado'].map(s=><div key={s} className="rounded-xl bg-slate-50 p-4"><div className="text-[10px] text-slate-400">{s}</div><div className="text-xl font-bold text-slate-800 mt-1">{data.leads.filter(l=>l.stage===s).length}</div></div>)}</div></div></div>
 </div></div>
}
