import { useMemo, useState } from 'react'
import { Plus, Search, MoreVertical, Pencil, Baby, Archive, WalletCards, UserRound, ChevronRight, X } from 'lucide-react'
import Modal from '../components/Modal'
export default function Families({data,setData,toast}){
 const [tab,setTab]=useState('familia'); const [q,setQ]=useState(''); const [familyStatus,setFamilyStatus]=useState('Active'); const [selected,setSelected]=useState(null); const [child,setChild]=useState(null); const [familyModal,setFamilyModal]=useState(false); const [childModal,setChildModal]=useState(false)
 const [familyForm,setFamilyForm]=useState({parentName:'',phone:'',centerName:'Namii Del Valle',status:'Active'}); const [childForm,setChildForm]=useState({name:'',familyId:'',gender:'',dob:'',centerName:'Namii Del Valle',status:'Inscrito'})
 const childrenOf=id=>data.children.filter(c=>String(c.familyId)===String(id)&&!c.archived)
 const families=useMemo(()=>data.families.filter(f=>(f.status||'Active')===familyStatus).filter(f=>{if(!q)return true;const z=q.toLowerCase();return f.parentName.toLowerCase().includes(z)||childrenOf(f.id).some(c=>c.name.toLowerCase().includes(z))}),[data.families,data.children,q,familyStatus])
 const openFamily=f=>{setFamilyForm({...f});setFamilyModal(true)}
 const saveFamily=()=>{if(!familyForm.parentName.trim())return toast('Ingresa el nombre del responsable');setData(d=>({...d,families:d.families.some(f=>f.id===familyForm.id)?d.families.map(f=>f.id===familyForm.id?familyForm:f):[...d.families,{...familyForm,id:Date.now(),registeredDate:new Date().toISOString().slice(0,10),membersCount:0}]}));setFamilyModal(false);toast('Familia guardada')}
 const archiveFamily=f=>{setData(d=>({...d,families:d.families.map(x=>x.id===f.id?{...x,status:x.status==='Archived'?'Active':'Archived'}:x)}));toast(f.status==='Archived'?'Familia restaurada':'Familia archivada')}
 const saveChild=()=>{if(!childForm.name.trim()||!childForm.familyId)return toast('Selecciona una familia y escribe el nombre del niño');const fam=data.families.find(f=>f.id===Number(childForm.familyId));const c={...childForm,id:Date.now(),familyId:Number(childForm.familyId),parentName:fam?.parentName||'',phone:fam?.phone||'',age:'',roomName:'Not enrolled',archived:false};setData(d=>({...d,children:[...d.children,c]}));setChildModal(false);toast('Niño registrado correctamente')}
 const archiveChild=c=>{setData(d=>({...d,children:d.children.map(x=>x.id===c.id?{...x,archived:!x.archived}:x)}));toast(c.archived?'Niño restaurado':'Niño archivado')}
 return <div className="flex-1 overflow-y-auto p-6 md:p-8 dot-pattern"><div className="max-w-7xl mx-auto space-y-6"><div className="bg-white/75 backdrop-blur-md p-6 rounded-2xl border border-teal-100/80 shadow-sm space-y-4"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-800">Familias y Niños</h1><p className="text-xs text-slate-500">Gestión integral de expedientes familiares, alumnos y matrículas</p></div><button onClick={()=>{setChildModal(tab==='nino');setFamilyModal(tab==='familia')}} className="bg-teal-700 hover:bg-teal-800 text-white text-xs font-semibold px-4 py-2.5 rounded-xl flex items-center"><Plus size={15} className="mr-1.5"/>{tab==='familia'? 'Registrar Familia':'Registrar Niño'}</button></div><div className="flex items-center space-x-1 border-b border-slate-200/80 pt-2 text-xs font-semibold"><button onClick={()=>setTab('familia')} className={`px-4 py-2.5 rounded-t-xl ${tab==='familia'?'text-teal-700 border-b-2 border-teal-700 bg-teal-50/50':'text-slate-500'}`}><UserRound size={14} className="inline mr-2"/>Familia</button><button onClick={()=>setTab('nino')} className={`px-4 py-2.5 rounded-t-xl ${tab==='nino'?'text-teal-700 border-b-2 border-teal-700 bg-teal-50/50':'text-slate-500'}`}><Baby size={14} className="inline mr-2"/>Niños</button></div></div>
 {tab==='familia'?<><div className="flex flex-col sm:flex-row gap-3"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar familia o niño..." className="w-full pl-9 py-2.5 rounded-xl border border-slate-200 text-xs"/></div><select value={familyStatus} onChange={e=>setFamilyStatus(e.target.value)} className="px-3 py-2.5 rounded-xl border border-slate-200 text-xs"><option>Active</option><option>Archived</option></select></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{families.map(f=><div key={f.id} className="bg-white rounded-2xl border border-teal-100/80 shadow-sm p-5"><div className="flex justify-between"><button onClick={()=>setSelected(f)} className="text-left"><h3 className="font-bold text-slate-800 text-sm hover:text-teal-700">{f.parentName}</h3><p className="text-[11px] text-slate-400 mt-1">{f.phone||'Sin teléfono'}</p></button><div className="flex gap-1"><button onClick={()=>openFamily(f)} className="p-2 rounded-lg hover:bg-slate-100"><Pencil size={14}/></button><button onClick={()=>archiveFamily(f)} className="p-2 rounded-lg hover:bg-slate-100"><MoreVertical size={14}/></button></div></div><div className="mt-5 pt-4 border-t border-slate-100"><div className="text-[10px] uppercase font-bold tracking-wide text-slate-400 mb-2">Niños</div>{childrenOf(f.id).map(c=><div key={c.id} className="flex items-center justify-between py-2"><button onClick={()=>setChild(c)} className="flex items-center gap-2 text-xs font-semibold text-slate-700"><span className="w-7 h-7 rounded-lg bg-teal-50 text-teal-700 flex items-center justify-center"><Baby size={14}/></span>{c.name}</button><ChevronRight size={14} className="text-slate-300"/></div>)}{childrenOf(f.id).length===0&&<div className="text-xs text-slate-400">No hay niños registrados</div>}<button onClick={()=>{setChildForm({...childForm,familyId:String(f.id)});setChildModal(true)}} className="mt-3 text-[11px] text-teal-700 font-semibold">+ Agregar hijo</button></div></div>)}</div></>:<div className="bg-white rounded-2xl border border-teal-100/80 overflow-hidden"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-400 uppercase text-[10px]"><tr><th className="px-5 py-3">Niño</th><th>Familia</th><th>Centro</th><th>Estado</th><th></th></tr></thead><tbody>{data.children.filter(c=>!c.archived&&(!q||c.name.toLowerCase().includes(q.toLowerCase()))).map(c=><tr key={c.id} className="border-t border-slate-100"><td className="px-5 py-3 font-semibold">{c.name}</td><td>{c.parentName}</td><td>{c.centerName}</td><td>{c.status}</td><td><button onClick={()=>setChild(c)} className="text-teal-700 font-semibold">Perfil</button></td></tr>)}</tbody></table></div>}
 <Modal open={familyModal} onClose={()=>setFamilyModal(false)} title="Familia"><div className="space-y-4"><label className="text-xs font-semibold block">Responsable<input value={familyForm.parentName||''} onChange={e=>setFamilyForm({...familyForm,parentName:e.target.value})} className="mt-1 w-full border border-slate-200 rounded-xl p-2.5"/></label><label className="text-xs font-semibold block">Teléfono<input value={familyForm.phone||''} onChange={e=>setFamilyForm({...familyForm,phone:e.target.value})} className="mt-1 w-full border border-slate-200 rounded-xl p-2.5"/></label><button onClick={saveFamily} className="w-full bg-teal-700 text-white py-2.5 rounded-xl text-xs font-semibold">Guardar</button></div></Modal>
 <Modal open={childModal} onClose={()=>setChildModal(false)} title="Registrar niño"><div className="space-y-4"><label className="text-xs font-semibold block">Familia<select value={childForm.familyId} onChange={e=>setChildForm({...childForm,familyId:e.target.value})} className="mt-1 w-full border border-slate-200 rounded-xl p-2.5"><option value="">Seleccionar...</option>{data.families.filter(f=>f.status==='Active').map(f=><option key={f.id} value={f.id}>{f.parentName}</option>)}</select></label><label className="text-xs font-semibold block">Nombre del niño<input value={childForm.name} onChange={e=>setChildForm({...childForm,name:e.target.value})} className="mt-1 w-full border border-slate-200 rounded-xl p-2.5"/></label><label className="text-xs font-semibold block">Fecha de nacimiento<input type="date" value={childForm.dob} onChange={e=>setChildForm({...childForm,dob:e.target.value})} className="mt-1 w-full border border-slate-200 rounded-xl p-2.5"/></label><button onClick={saveChild} className="w-full bg-teal-700 text-white py-2.5 rounded-xl text-xs font-semibold">Guardar</button></div></Modal>
 <Modal open={!!selected} onClose={()=>setSelected(null)} title={`Familia · ${selected?.parentName||''}`}><div className="space-y-4">{selected&&<><div className="grid grid-cols-2 gap-3"><div className="bg-slate-50 rounded-xl p-3"><div className="text-[10px] text-slate-400">Teléfono</div><div className="text-xs font-semibold mt-1">{selected.phone}</div></div><div className="bg-slate-50 rounded-xl p-3"><div className="text-[10px] text-slate-400">Centro</div><div className="text-xs font-semibold mt-1">{selected.centerName}</div></div></div><div><div className="text-[10px] uppercase font-bold text-slate-400 mb-2">Niños</div>{childrenOf(selected.id).map(c=><div className="p-3 border border-slate-100 rounded-xl mb-2 flex justify-between" key={c.id}><span className="text-xs font-semibold">{c.name}</span><button onClick={()=>{setChild(c);setSelected(null)}} className="text-teal-700 text-xs">Perfil</button></div>)}</div></>}</div></Modal>
 <Modal open={!!child} onClose={()=>setChild(null)} title={`Perfil · ${child?.name||''}`}><div className="space-y-4">{child&&<><div className="grid grid-cols-2 gap-3"><div className="bg-slate-50 p-3 rounded-xl"><div className="text-[10px] text-slate-400">Familia</div><div className="text-xs font-semibold mt-1">{child.parentName}</div></div><div className="bg-slate-50 p-3 rounded-xl"><div className="text-[10px] text-slate-400">Centro</div><div className="text-xs font-semibold mt-1">{child.centerName}</div></div></div><button onClick={()=>{archiveChild(child);setChild(null)}} className="w-full border border-rose-200 text-rose-600 py-2.5 rounded-xl text-xs font-semibold flex items-center justify-center gap-2"><Archive size={14}/>{child.archived?'Restaurar niño':'Archivar niño'}</button></>}</div></Modal>
 </div></div>
}
