import { useMemo, useState } from 'react'
import { Plus, Search, Pencil, Trash2, Users, Baby, UserPlus } from 'lucide-react'
import Modal from '../components/Modal'
export default function Rooms({data,setData,toast}){
 const [q,setQ]=useState(''); const [modal,setModal]=useState(false); const [editing,setEditing]=useState(null)
 const [form,setForm]=useState({name:'',ageGroup:'',capacity:10,ratio:'1:6',staffIds:[],enrolledChildIds:[]})
 const list=useMemo(()=>data.rooms.filter(r=>r.name.toLowerCase().includes(q.toLowerCase())||(r.ageGroup||'').toLowerCase().includes(q.toLowerCase())),[data.rooms,q])
 const open=(r=null)=>{setEditing(r);setForm(r?JSON.parse(JSON.stringify(r)):{name:'',ageGroup:'',capacity:10,ratio:'1:6',staffIds:[],enrolledChildIds:[]});setModal(true)}
 const save=()=>{if(!form.name.trim())return toast('Escribe un nombre para el grupo'); setData(d=>({...d,rooms:editing?d.rooms.map(r=>r.id===editing.id?{...editing,...form}:r):[...d.rooms,{...form,id:Date.now(),enrolled:form.enrolledChildIds.length}]}));setModal(false);toast(editing?'Grupo actualizado':'Grupo creado')}
 const remove=id=>{if(confirm('¿Eliminar este grupo?')){setData(d=>({...d,rooms:d.rooms.filter(r=>r.id!==id)}));toast('Grupo eliminado')}}
 return <div className="flex-1 overflow-y-auto p-6 md:p-8 dot-pattern"><div className="max-w-7xl mx-auto space-y-6">
  <div className="flex flex-col sm:flex-row justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-800">Grupos / Salas</h1><p className="text-xs text-slate-500">Gestiona grupos, capacidad y responsables.</p></div><button onClick={()=>open()} className="bg-teal-700 hover:bg-teal-800 text-white text-xs font-semibold px-4 py-2.5 rounded-xl flex items-center gap-1.5"><Plus size={15}/> Agregar grupo</button></div>
  <div className="bg-white/75 rounded-2xl border border-teal-100/80 p-4"><div className="relative max-w-sm"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar grupo..." className="w-full pl-9 pr-3 py-2.5 rounded-xl border border-slate-200 text-xs outline-none focus:border-teal-400"/></div></div>
  <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{list.map(r=><div key={r.id} className="bg-white rounded-2xl border border-teal-100/80 shadow-sm overflow-hidden"><div className="p-5"><div className="flex justify-between gap-3"><div><h3 className="font-bold text-slate-800 text-sm">{r.name}</h3><p className="text-[11px] text-slate-400 mt-1">{r.ageGroup}</p></div><div className="flex gap-1"><button onClick={()=>open(r)} className="p-2 rounded-lg hover:bg-slate-100 text-slate-500"><Pencil size={14}/></button><button onClick={()=>remove(r.id)} className="p-2 rounded-lg hover:bg-rose-50 text-rose-500"><Trash2 size={14}/></button></div></div><div className="grid grid-cols-2 gap-2 mt-5"><div className="rounded-xl bg-teal-50/70 p-3"><div className="text-[10px] text-slate-400">Capacidad</div><div className="font-bold text-slate-800 mt-1">{r.enrolled||r.enrolledChildIds?.length||0}/{r.capacity}</div></div><div className="rounded-xl bg-slate-50 p-3"><div className="text-[10px] text-slate-400">Ratio</div><div className="font-bold text-slate-800 mt-1">{r.ratio}</div></div></div></div><div className="border-t border-slate-100 p-5 space-y-4"><div><div className="text-[10px] uppercase tracking-wide text-slate-400 font-bold mb-2 flex items-center gap-1"><Users size={12}/> Staff</div>{(r.staffIds||[]).length?<div className="space-y-1">{r.staffIds.map(id=>{const s=data.staff.find(x=>x.id===id);return s?<div key={id} className="text-xs text-slate-700">{s.name}</div>:null})}</div>:<div className="text-xs text-slate-400">No staff assigned</div>}<button onClick={()=>toast('Asignación de staff lista para conectar')} className="mt-2 text-[11px] font-semibold text-teal-700 flex items-center gap-1"><UserPlus size={12}/> Asignar staff</button></div><div><div className="text-[10px] uppercase tracking-wide text-slate-400 font-bold mb-2 flex items-center gap-1"><Baby size={12}/> Niños inscritos</div>{(r.enrolledChildIds||[]).length?<div className="space-y-1">{r.enrolledChildIds.map(id=>{const c=data.children.find(x=>x.id===id);return c?<div key={id} className="text-xs text-slate-700">{c.name}</div>:null})}</div>:<div className="text-xs text-slate-400">No children enrolled</div>}<button onClick={()=>toast('Inscripción de niño lista para conectar')} className="mt-2 text-[11px] font-semibold text-teal-700 flex items-center gap-1"><Plus size={12}/> Inscribir niño</button></div></div></div>)}</div>
  <Modal open={modal} onClose={()=>setModal(false)} title={editing?'Editar grupo':'Agregar grupo'}><div className="space-y-4"><label className="block text-xs font-semibold text-slate-700">Nombre<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-1 w-full px-3 py-2.5 border border-slate-200 rounded-xl outline-none"/></label><label className="block text-xs font-semibold text-slate-700">Etapa / edad<input value={form.ageGroup} onChange={e=>setForm({...form,ageGroup:e.target.value})} className="mt-1 w-full px-3 py-2.5 border border-slate-200 rounded-xl outline-none"/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-700">Capacidad<input type="number" value={form.capacity} onChange={e=>setForm({...form,capacity:Number(e.target.value)})} className="mt-1 w-full px-3 py-2.5 border border-slate-200 rounded-xl"/></label><label className="text-xs font-semibold text-slate-700">Ratio<input value={form.ratio} onChange={e=>setForm({...form,ratio:e.target.value})} className="mt-1 w-full px-3 py-2.5 border border-slate-200 rounded-xl"/></label></div><button onClick={save} className="w-full bg-teal-700 text-white py-2.5 rounded-xl text-xs font-semibold">Guardar</button></div></Modal>
 </div></div>
}
